const foot = {
  "Cold feet": [89, false],
  "Changes in the nails": [91, false],
  "Tremor at rest": [115, false],
  "Problems with the sense of touch in the feet": [130, false],
  "Tremor on movement": [132, false],
  "Leg cramps": [146, false],
  Tingling: [201, false],
  "Discoloration of nails": [216, false],
  "Foot pain": [255, false],
  "Involuntary movements": [257, false],
  "Brittleness of nails": [979, false],
  Agitation: [981, false],
  "Limited mobility of the ankle": [992, false],
  "Foot swelling": [1002, false],
  "Toe swelling": [1003, false],
};
const legsGeneral = {
  "Pain in the limbs": [12, false],
  "Joint pain": [27, false],
  Cramps: [94, false],
  "Pain radiating to the leg": [103, false],
  "Physical inactivity": [118, false],
  "Muscle stiffness": [119, false],
  Paralysis: [140, false],
  "Feeling of tension in the legs": [145, false],
  "Leg cramps": [146, false],
  "Pain in the bones": [155, false],
  "Bone fracture": [156, false],
  "Muscle pain": [177, false],
  "Stress-related leg pain": [185, false],
  "Joint swelling": [193, false],
  "Joint effusion": [194, false],
  "Limited mobility of the leg": [195, false],
  Immobilization: [197, false],
  "Joint instability": [198, false],
  "Joint redness": [230, false],
  "Leg swelling": [231, false],
  "Muscular atrophy in the leg": [252, false],
  "Muscular weakness in the leg": [253, false],
  "Numbness in the leg": [254, false],
  "Involuntary movements": [257, false],
  "Weakness or numbness on right or left side of body": [972, true],
  Agitation: [981, false],
  "Muscle weakness": [987, false],
  "Difficulty with gait": [1005, false],
  "Enlarged calf": [1006, false],
  "Leg pain": [1010, false],
};
const lowerLegAnkle = {
  "Pain in the calves": [142, false],
  "Leg ulcer": [143, false],
  "Feeling of tension in the legs": [145, false],
  "Leg cramps": [146, false],
  "Ankle swelling": [147, false],
  "Marked veins": [232, false],
  "Limited mobility of the ankle": [992, false],
  "Knee deformity": [994, false],
  "Ankle deformity": [996, false],
  "Foot swelling": [1002, false],
  "Enlarged calf": [1006, false],
  "Leg pain": [1010, false],
};
const thighKnee = {
  "Feeling of tension in the legs": [145, false],
  "Leg cramps": [146, false],
  "Knee pain": [256, false],
  "Absence of a pulse": [984, true],
  "Leg pain": [1010, false],
};
const toes = {
  "Joint pain": [27, false],
  "Changes in the nails": [91, false],
  Tingling: [201, false],
  "Discoloration of nails": [216, false],
  "Joint redness": [230, false],
  "Brittleness of nails": [979, false],
  "Toe deformity": [997, false],
  "Toe swelling": [1003, false],
};

module.exports = { foot, legsGeneral, lowerLegAnkle, thighKnee, toes };
